pipeline:
  identifier: Build_avkalyan_DevSecOps_Harness_1742071135000
  name: Build DevSecOps-Harness
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: avkalyan/DevSecOps-Harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: maven build
                  identifier: maven_build
                  spec:
                    shell: Bash
                    command: |-
                      export M2_HOME=/usr/local/Cellar/maven/3.9.9
                      export PATH=$PATH:$M2_HOME/bin
                      mvn clean install -nsu -DskipMunitTests
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
