pipeline:
  identifier: Build_avkalyan_DevSecOps_Harness_1742069594610
  name: Build DevSecOps-Harness
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run maven build
                  identifier: Run_maven_build
                  spec:
                    shell: Bash
                    command: |-
                      export M2_HOME=/usr/local/Cellar/maven/3.9.9
                      export PATH=$PATH:$M2_HOME/bin
                      mvn clean install -nsu -DskipMunitTests -Dlicense.skip=true
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          buildIntelligence:
            enabled: false
        type: CI
        delegateSelectors:
          - docker-delegate
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: DevSecOps-Harness
        build: <+input>
        sparseCheckout: []
