pipeline:
  identifier: Build_avkalyan_DevSecOps_Harness_1742065258449
  name: Build DevSecOps-Harness
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: avkalyan/DevSecOps-Harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        delegateSelectors:
          - docker-delegate
          - helm-delegate
          - macos-amd64
